export default {
	email: '',
	firstName: '',
	lastName: '',
	phone: '00000000000',
	dateOfBirth: '',
	locationId: [1],
	positionId: [1],
	hireDate: new Date().toLocaleDateString(),
	address: 'Unknown',
	region: null,
	commune: null,
	isActive: false,
	isAssociated: true,
	avatarUrl: 'https://randomuser.me/api/portraits/men/57.jpg',
	contract: '',
	employeeId: '',
};
